[[[0,"c:\\Users\\madio\\anaconda3\\Lib\\site-packages\\service_identity\\__init__.py","","",null,0],[false,[["CertificateError",3,2,["CertificateError",[0,"c:\\Users\\madio\\anaconda3\\Lib\\site-packages\\service_identity\\exceptions.py","","",null,0],5]],["SubjectAltNameWarning",3,2,["SubjectAltNameWarning",[0,"c:\\Users\\madio\\anaconda3\\Lib\\site-packages\\service_identity\\exceptions.py","","",null,0],5]],["VerificationError",3,2,["VerificationError",[0,"c:\\Users\\madio\\anaconda3\\Lib\\site-packages\\service_identity\\exceptions.py","","",null,0],5]]]]]]